name: Events Demo 1
on: 
  pull_request:
    types:
      - opened
    branches:
      - main # trigger for main branch
      - 'dev-*' # trigger for any branch which start with dev- forexample : dev-panel or dev-admin-dashboard
      - 'feature/**' # trigger for any branch which start with feature/ forexample: feature/chatbot or feature/admindasboard/settings
  workflow_dispatch:
  push:
    branches:
      - main # trigger for main branch
      - 'dev-*' # trigger for any branch which start with dev- forexample : dev-panel or dev-admin-dashboard
      - 'feature/**' # trigger for any branch which start with feature/ forexample: feature/chatbot or feature/admindasboard/settings
    paths-ignore:
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."